name: EasyCarts
main: com.github.xericore.easycarts.EasyCarts
version: ${project.version}
api-version: 1.13

commands:
   easycarts:
      description: Sets new minecart speed limit.
      usage: |
         /easycarts reload|slowwhenempty OR push|boost|maxspeed <value>
permissions:
    easycarts.admin:
      description: Gives access to all easycarts features. 
      default: op